### ISSUE TITLE
Fix OpenMetadata entities link

### ISSUE THREAD

**Issue by giucris** [agile-lab-dev/Data-Product-Specification#11]
OpenMetadata has released a new version and it seems that they have introduced backward compatibility problems with the links used in our Readme. 

The following link provided by the Readme does not work any more:
https://docs.open-metadata.org/openmetadata/schemas/entities/tagcategory
https://docs.open-metadata.org/openmetadata/schemas/entities/table#tabledata
https://docs.open-metadata.org/openmetadata/schemas/entities/table#tableprofile

**Comment by SpyQuel** [comment]
I tried to fix all the broken links and add the CUE validation for OpenMetadata structures.
I think we can close this issue.
