### ISSUE TITLE
Add bi-temporality references in data contract

### ISSUE THREAD

**Issue by erond** [agile-lab-dev/Data-Product-Specification#18]
## scenario summary 

One of data as a product properties is bi-temporality in every output port 

## problem statement

being a property of every output port and considering it a foundational property that guarantees to consumers the possibility to time travel over the 2 temporal dimensions, this property should be explicitly managed as part of the output port’s data contract.

Also, it should enable automated checks as part of the computational federated governance.

## proposed solution 

Add in the data contract section 2 new String fields to be valorized with the output port’s corresponding technical and business temporal references, which should also be checked against the provided output port’s schema.

**Comment by agile-lab** [comment]
@erond, could you move one with a proposal to discuss?
